'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.269
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property action_paste() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("action_paste", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property action_print() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("action_print", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property action_save() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("action_save", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property action_save1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("action_save1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property AudioHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AudioHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property boldAction1_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boldAction1_Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bullet_arrow_down() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bullet_arrow_down", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bullet_arrow_up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bullet_arrow_up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Color_linecolor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Color_linecolor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property comment_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("comment_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property comment_delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("comment_delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property comment_edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("comment_edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property comment_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("comment_new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property comment_yellow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("comment_yellow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property comments() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("comments", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property control_fastforward() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("control_fastforward", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property control_fastforward_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("control_fastforward_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Control_PageSetupDialog() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Control_PageSetupDialog", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property control_pause() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("control_pause", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property control_pause_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("control_pause_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property control_play() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("control_play", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property control_play_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("control_play_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Control_PrintPreviewControl() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Control_PrintPreviewControl", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property control_repeat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("control_repeat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property control_repeat_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("control_repeat_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property control_rewind() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("control_rewind", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property control_rewind_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("control_rewind_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property copyAction1_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("copyAction1_Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cutAction1_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cutAction1_Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property DOC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DOC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property email() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("email", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Filmroll() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Filmroll", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Forecolor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Forecolor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property help() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icon_accept() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_accept", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icon_alert() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_alert", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property icon_favourites() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_favourites", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property information() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("information", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property italicAction1_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("italicAction1_Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property LineColorHS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LineColorHS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logonew01_800x600() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logonew01_800x600", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property logonew01_800x600_outline() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logonew01_800x600_outline", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property OPENFOLD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OPENFOLD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property page_video() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page_video", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property page_white_compressed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page_white_compressed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property page_white_text() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("page_white_text", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pasteAction1_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pasteAction1_Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property printer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("printer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property redoAction1_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("redoAction1_Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property splitter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("splitter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Information.
        '''</summary>
        Friend ReadOnly Property STR_ABOUT() As String
            Get
                Return ResourceManager.GetString("STR_ABOUT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Activity folder already exists.
        '''</summary>
        Friend ReadOnly Property STR_ACTIVITY_FOLDER_EXISTS() As String
            Get
                Return ResourceManager.GetString("STR_ACTIVITY_FOLDER_EXISTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Activity has been modified. Do you want to save before closing?.
        '''</summary>
        Friend ReadOnly Property STR_ACTIVITY_MODIFIED() As String
            Get
                Return ResourceManager.GetString("STR_ACTIVITY_MODIFIED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Authoring.
        '''</summary>
        Friend ReadOnly Property STR_AUTHORING() As String
            Get
                Return ResourceManager.GetString("STR_AUTHORING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Comment.
        '''</summary>
        Friend ReadOnly Property STR_COMMENT() As String
            Get
                Return ResourceManager.GetString("STR_COMMENT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Duration.
        '''</summary>
        Friend ReadOnly Property STR_DURATION() As String
            Get
                Return ResourceManager.GetString("STR_DURATION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Must always have &apos;Duration&apos; &gt;= 0.
        '''</summary>
        Friend ReadOnly Property STR_DURATION_POSITIVE() As String
            Get
                Return ResourceManager.GetString("STR_DURATION_POSITIVE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to End time.
        '''</summary>
        Friend ReadOnly Property STR_END_TIME() As String
            Get
                Return ResourceManager.GetString("STR_END_TIME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Must always have &apos;End Time&apos; &gt;= &apos;Start Time&apos;.
        '''</summary>
        Friend ReadOnly Property STR_ENDTIME_GREATEREQUAL_STARTTIME() As String
            Get
                Return ResourceManager.GetString("STR_ENDTIME_GREATEREQUAL_STARTTIME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter your feedback here....
        '''</summary>
        Friend ReadOnly Property STR_ENTER_FEEDBACK() As String
            Get
                Return ResourceManager.GetString("STR_ENTER_FEEDBACK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter folder name.
        '''</summary>
        Friend ReadOnly Property STR_ENTER_FOLDER_NAME() As String
            Get
                Return ResourceManager.GetString("STR_ENTER_FOLDER_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error.
        '''</summary>
        Friend ReadOnly Property STR_ERROR() As String
            Get
                Return ResourceManager.GetString("STR_ERROR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to exit the application? If you don&apos;t the application might not behave properly..
        '''</summary>
        Friend ReadOnly Property STR_EXCEPTION_EXIT() As String
            Get
                Return ResourceManager.GetString("STR_EXCEPTION_EXIT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please use Help/Send feedback menu option to report the error details..
        '''</summary>
        Friend ReadOnly Property STR_EXCEPTION_FEEDBACK() As String
            Get
                Return ResourceManager.GetString("STR_EXCEPTION_FEEDBACK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File not found.
        '''</summary>
        Friend ReadOnly Property STR_FILE_NOT_FOUND() As String
            Get
                Return ResourceManager.GetString("STR_FILE_NOT_FOUND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Folder not found.
        '''</summary>
        Friend ReadOnly Property STR_FOLDER_NOT_FOUND() As String
            Get
                Return ResourceManager.GetString("STR_FOLDER_NOT_FOUND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Help file not found.
        '''</summary>
        Friend ReadOnly Property STR_HELP_NOT_FOUND() As String
            Get
                Return ResourceManager.GetString("STR_HELP_NOT_FOUND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid style parameter to &apos;ChangeFontStyle&apos; method.
        '''</summary>
        Friend ReadOnly Property STR_INVALID_CHANGEFONTSTYLE_PARAM() As String
            Get
                Return ResourceManager.GetString("STR_INVALID_CHANGEFONTSTYLE_PARAM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Folder name can&apos;t contain the following chars.
        '''</summary>
        Friend ReadOnly Property STR_INVALID_FOLDER_NAME_CHARS() As String
            Get
                Return ResourceManager.GetString("STR_INVALID_FOLDER_NAME_CHARS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid value.
        '''</summary>
        Friend ReadOnly Property STR_INVALID_VALUE() As String
            Get
                Return ResourceManager.GetString("STR_INVALID_VALUE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Couldn&apos;t load file.
        '''</summary>
        Friend ReadOnly Property STR_LOAD_FILE_FAILED() As String
            Get
                Return ResourceManager.GetString("STR_LOAD_FILE_FAILED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New activity folder name?.
        '''</summary>
        Friend ReadOnly Property STR_NEW_ACTIVITY_FOLDER_NAME() As String
            Get
                Return ResourceManager.GetString("STR_NEW_ACTIVITY_FOLDER_NAME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This is not an activity folder.
        '''</summary>
        Friend ReadOnly Property STR_NOT_ACTIVITY_FOLDER() As String
            Get
                Return ResourceManager.GetString("STR_NOT_ACTIVITY_FOLDER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Couldn&apos;t open network address (URL).
        '''</summary>
        Friend ReadOnly Property STR_OPEN_URL_FAILED() As String
            Get
                Return ResourceManager.GetString("STR_OPEN_URL_FAILED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Could not pack activity folder.
        '''</summary>
        Friend ReadOnly Property STR_PACK_ACTIVITY_FOLDER_FAILED() As String
            Get
                Return ResourceManager.GetString("STR_PACK_ACTIVITY_FOLDER_FAILED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You can&apos;t select an activity folder as parent folder.
        '''</summary>
        Friend ReadOnly Property STR_PARENT_FOLDER_IS_ACTIVITY() As String
            Get
                Return ResourceManager.GetString("STR_PARENT_FOLDER_IS_ACTIVITY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Question.
        '''</summary>
        Friend ReadOnly Property STR_QUESTION() As String
            Get
                Return ResourceManager.GetString("STR_QUESTION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to remove subtitle&apos;s student comment?.
        '''</summary>
        Friend ReadOnly Property STR_REMOVE_SUBTITLE_STUDENT_COMMENT() As String
            Get
                Return ResourceManager.GetString("STR_REMOVE_SUBTITLE_STUDENT_COMMENT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to remove subtitle&apos;s teacher comment?.
        '''</summary>
        Friend ReadOnly Property STR_REMOVE_SUBTITLE_TEACHER_COMMENT() As String
            Get
                Return ResourceManager.GetString("STR_REMOVE_SUBTITLE_TEACHER_COMMENT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Couldn&apos;t save file.
        '''</summary>
        Friend ReadOnly Property STR_SAVE_FILE_FAILED() As String
            Get
                Return ResourceManager.GetString("STR_SAVE_FILE_FAILED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select activity folder.
        '''</summary>
        Friend ReadOnly Property STR_SELECT_ACTIVITY_FOLDER() As String
            Get
                Return ResourceManager.GetString("STR_SELECT_ACTIVITY_FOLDER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select parent folder for new activity subfolder.
        '''</summary>
        Friend ReadOnly Property STR_SELECT_PARENT_FOLDER_NEW_ACTIVITY() As String
            Get
                Return ResourceManager.GetString("STR_SELECT_PARENT_FOLDER_NEW_ACTIVITY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select parent folder to unpack activity subfolder.
        '''</summary>
        Friend ReadOnly Property STR_SELECT_PARENT_FOLDER_UNPACK_ACTIVITY() As String
            Get
                Return ResourceManager.GetString("STR_SELECT_PARENT_FOLDER_UNPACK_ACTIVITY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Start time.
        '''</summary>
        Friend ReadOnly Property STR_START_TIME() As String
            Get
                Return ResourceManager.GetString("STR_START_TIME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Student.
        '''</summary>
        Friend ReadOnly Property STR_STUDENT_COMMENT() As String
            Get
                Return ResourceManager.GetString("STR_STUDENT_COMMENT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Subtitle.
        '''</summary>
        Friend ReadOnly Property STR_SUBTITLE() As String
            Get
                Return ResourceManager.GetString("STR_SUBTITLE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Teacher.
        '''</summary>
        Friend ReadOnly Property STR_TEACHER_COMMENT() As String
            Get
                Return ResourceManager.GetString("STR_TEACHER_COMMENT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Could not unpack activity file.
        '''</summary>
        Friend ReadOnly Property STR_UNPACK_FAILED() As String
            Get
                Return ResourceManager.GetString("STR_UNPACK_FAILED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Version.
        '''</summary>
        Friend ReadOnly Property STR_VERSION() As String
            Get
                Return ResourceManager.GetString("STR_VERSION", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Volume.
        '''</summary>
        Friend ReadOnly Property STR_VOLUME() As String
            Get
                Return ResourceManager.GetString("STR_VOLUME", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning.
        '''</summary>
        Friend ReadOnly Property STR_WARNING() As String
            Get
                Return ResourceManager.GetString("STR_WARNING", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property text_align_center() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_align_center", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property text_align_left() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_align_left", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property text_align_right() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_align_right", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property text_list_bullets() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_list_bullets", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property text_strikethrough() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("text_strikethrough", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property underlineAction1_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("underlineAction1_Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property undoAction1_Image() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("undoAction1_Image", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property world_go() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("world_go", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
