'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1378
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Encoding:.
        '''</summary>
        Friend ReadOnly Property STR_ENCODING() As String
            Get
                Return ResourceManager.GetString("STR_ENCODING", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Couldn&apos;t show file open dialog.
        '''</summary>
        Friend ReadOnly Property STR_FILE_OPEN_DIALOG_FAILED() As String
            Get
                Return ResourceManager.GetString("STR_FILE_OPEN_DIALOG_FAILED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Couldn&apos;t show file save dialog.
        '''</summary>
        Friend ReadOnly Property STR_FILE_SAVE_DIALOG_FAILED() As String
            Get
                Return ResourceManager.GetString("STR_FILE_SAVE_DIALOG_FAILED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Folder not found.
        '''</summary>
        Friend ReadOnly Property STR_FOLDER_NOT_FOUND() As String
            Get
                Return ResourceManager.GetString("STR_FOLDER_NOT_FOUND", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid SRT format.
        '''</summary>
        Friend ReadOnly Property STR_INVALID_SRT() As String
            Get
                Return ResourceManager.GetString("STR_INVALID_SRT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid TTS format.
        '''</summary>
        Friend ReadOnly Property STR_INVALID_TTS() As String
            Get
                Return ResourceManager.GetString("STR_INVALID_TTS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not implemented!.
        '''</summary>
        Friend ReadOnly Property STR_NOT_IMPLEMENTED() As String
            Get
                Return ResourceManager.GetString("STR_NOT_IMPLEMENTED", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save file as.
        '''</summary>
        Friend ReadOnly Property STR_SAVEAS() As String
            Get
                Return ResourceManager.GetString("STR_SAVEAS", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
